import LocalFont from "next/font/local";
import "./globals.css";

const font = LocalFont({ src:[{
  path:"../public/HussarBoldWeb-bf92.woff"
}] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <h1>header</h1>
        {children}
        <h1>footer</h1>
      </body>
    </html>
  );
}
