
import Image from "next/image";
import { Button } from "./Button";
import styles from "./page.module.css";

export const metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default async function Home() {
  const res = await fetch('http://localhost:3000/api/users');
  const data =  await res.json();

   const url = "https://plus.unsplash.com/premium_photo-1717529138029-5b049119cfb1?q=80&w=1897&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

  return (
    <main className={styles.main}>
      <ul>
        {
          data?.map(({name, id})=><li className={styles.li} key={id} >{name}</li>)
        }
      </ul>
      {/* <div>
        <img src={url} style={{
          height:"400px",
          width:"200px"
        }} />
      </div>
        <div>
          <Image src={url} height={400} width={200} />
        </div>
      <Button /> */}
    </main>
  );
}
